services:
    backend:
        # build new image for backend
        build:
            context: .
            dockerfile: Dockerfile
        # if you want to pull from docker hub un comment the followoing
        # image: fraolbmax/guzolink-backend:latest
        container_name: guzolink-backend
        restart: unless-stopped
        volumes:
            - uploads_data:/app/uploads
        env_file:
            - ./.env.production

        depends_on:
            mongodb:
                condition: service_healthy
            redis:
                condition: service_healthy

        ports:
            - "127.0.0.1:5000:5000"

        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--spider",
                    "-q",
                    "http://localhost:5000/health",
                ]
            interval: 30s
            timeout: 5s
            retries: 3

    mongodb:
        image: mongo:latest
        container_name: guzolink-mongodb
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 10s

        restart: unless-stopped

        volumes:
            - mongodb_data:/data/db

    redis:
        image: redis:7-alpine
        restart: unless-stopped
        volumes:
            - redis_data:/data

        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 10
            start_period: 5s

volumes:
    mongodb_data:
    uploads_data:
    redis_data:
